version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: libp2p-utils
    versions:
    - 0.3.0
    - 0.3.1
  - dependency-name: mafmt
    versions:
    - 9.0.0
  - dependency-name: multiaddr
    versions:
    - 9.0.1
  - dependency-name: multibase
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.4
  - dependency-name: aegir
    versions:
    - 31.0.0
    - 31.0.1
    - 31.0.3
  - dependency-name: uint8arrays
    versions:
    - 2.0.5
    - 2.1.0
